# Generated by Django 5.2.15 on 2026-07-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("BUYER", "Người mua"),
                    ("FARMER", "Nông dân / Nhà sản xuất"),
                    ("AUDITOR", "Kiểm định viên / Auditor"),
                    ("ADMIN", "Quản trị viên"),
                ],
                default="BUYER",
                max_length=10,
            ),
        ),
    ]
