# Generated by Django 5.2.15 on 2026-07-06 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Số điện thoại phải bắt đầu bằng số 0 và gồm 10 hoặc 11 chữ số.",
                        regex="^0\\d{9,10}$",
                    )
                ],
                verbose_name="Số điện thoại",
            ),
        ),
    ]
