# Generated by Django 5.2.15 on 2026-07-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Họ và tên"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Số điện thoại"),
                ),
                (
                    "shipping_address",
                    models.TextField(verbose_name="Địa chỉ giao hàng"),
                ),
                (
                    "total_price",
                    models.IntegerField(default=0, verbose_name="Tổng tiền (VND)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ xử lý"),
                            ("CONFIRMED", "Đã xác nhận"),
                            ("SHIPPED", "Đang giao"),
                            ("DELIVERED", "Đã giao"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đặt"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Đơn hàng",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Số lượng"),
                ),
                ("price", models.IntegerField(verbose_name="Đơn giá lúc mua")),
            ],
            options={
                "verbose_name": "Chi tiết đơn hàng",
                "verbose_name_plural": "Chi tiết đơn hàng",
            },
        ),
    ]
