# Generated by Django 5.2.15 on 2026-07-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_provider",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Đơn vị vận chuyển"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ duyệt"),
                    ("APPROVED", "Đã duyệt"),
                    ("REJECTED", "Từ chối"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Trạng thái duyệt",
            ),
        ),
    ]
