# Generated by Django 5.2.15 on 2026-07-06 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_shipping_provider_orderitem_status"),
        ("products", "0010_remove_product_batch_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.batch",
                verbose_name="Lô sản phẩm",
            ),
        ),
    ]
