# Generated by Django 5.2.15 on 2026-07-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên danh mục")),
                ("slug", models.SlugField(unique=True)),
                (
                    "emoji",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Biểu tượng"
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Danh mục",
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Tên nông trại"),
                ),
                ("region", models.CharField(max_length=100, verbose_name="Vùng miền")),
                ("description", models.TextField(verbose_name="Mô tả nông trại")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Link ảnh nông trại"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nông trại",
                "verbose_name_plural": "Nông trại",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên sản phẩm")),
                ("slug", models.SlugField(unique=True)),
                ("origin", models.CharField(max_length=200, verbose_name="Xuất xứ")),
                ("price", models.IntegerField(verbose_name="Giá bán (VND)")),
                ("unit", models.CharField(max_length=50, verbose_name="Đơn vị tính")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        verbose_name="Đánh giá",
                    ),
                ),
                (
                    "reviews_count",
                    models.IntegerField(default=0, verbose_name="Số lượng đánh giá"),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nhãn (Badge)"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Link ảnh sản phẩm"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Mô tả sản phẩm"),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Còn hàng"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Số lô hàng"
                    ),
                ),
                (
                    "harvest_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày thu hoạch"
                    ),
                ),
                (
                    "blockchain_tx_hash",
                    models.CharField(
                        blank=True,
                        max_length=66,
                        null=True,
                        verbose_name="Mã giao dịch Blockchain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Sản phẩm",
                "ordering": ["-created_at"],
            },
        ),
    ]
