# Generated by Django 5.2.15 on 2026-07-04 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên danh mục blog"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Danh mục blog",
                "verbose_name_plural": "Danh mục blog",
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.TextField(verbose_name="Tóm tắt ngắn")),
                ("content", models.TextField(verbose_name="Nội dung bài viết")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Link ảnh đại diện"
                    ),
                ),
                (
                    "published_date",
                    models.DateField(auto_now_add=True, verbose_name="Ngày đăng"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="products.blogcategory",
                        verbose_name="Danh mục",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bài viết blog",
                "verbose_name_plural": "Bài viết blog",
                "ordering": ["-published_date"],
            },
        ),
    ]
