# Generated by Django 5.2.15 on 2026-07-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_blogcategory_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm",
            name="description",
        ),
        migrations.AddField(
            model_name="farm",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Được duyệt"),
        ),
    ]
