# Generated by Django 5.2.15 on 2026-07-04 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_farm_description_farm_approved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={
                "verbose_name": "Nhà cung cấp",
                "verbose_name_plural": "Nhà cung cấp",
            },
        ),
        migrations.AddField(
            model_name="farm",
            name="description",
            field=models.TextField(blank=True, verbose_name="Giới thiệu doanh nghiệp"),
        ),
        migrations.AddField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email liên hệ"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Số điện thoại liên hệ"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="tax_code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Mã số thuế"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Link ảnh đại diện"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Tên nhà cung cấp"),
        ),
        migrations.AlterField(
            model_name="farm",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Chủ doanh nghiệp",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="region",
            field=models.CharField(max_length=100, verbose_name="Khu vực/Vùng miền"),
        ),
    ]
