# Generated by Django 5.2.15 on 2026-07-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_farm_options_farm_description_farm_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="province",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Tỉnh/Thành phố"
            ),
        ),
    ]
