# Generated by Django 5.2.15 on 2026-07-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_farm_province"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="emoji",
        ),
    ]
