# Generated by Django 5.2.15 on 2026-07-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_favoriteproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="badge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Không có"),
                    ("Organic", "Organic"),
                    ("Bán chạy", "Bán chạy"),
                    ("VietGAP", "VietGAP"),
                    ("Local", "Local"),
                    ("Thuần chay", "Thuần chay"),
                    ("Non-GMO", "Non-GMO"),
                ],
                max_length=50,
                verbose_name="Nhãn (Badge)",
            ),
        ),
    ]
