# Generated by Django 5.2.15 on 2026-07-06 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_badge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="batch_number",
        ),
        migrations.RemoveField(
            model_name="product",
            name="blockchain_tx_hash",
        ),
        migrations.RemoveField(
            model_name="product",
            name="harvest_date",
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Mã số lô hàng"
                    ),
                ),
                (
                    "initial_quantity",
                    models.PositiveIntegerField(
                        verbose_name="Số lượng gieo giống ban đầu"
                    ),
                ),
                (
                    "remaining_quantity",
                    models.PositiveIntegerField(verbose_name="Số lượng tồn kho của lô"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CULTIVATING", "Đang canh tác"),
                            ("HARVESTED", "Đã thu hoạch (Sẵn sàng bán)"),
                            ("OUT_OF_STOCK", "Hết hàng"),
                        ],
                        default="CULTIVATING",
                        max_length=20,
                    ),
                ),
                ("seeding_date", models.DateField(verbose_name="Ngày gieo giống")),
                (
                    "harvest_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày thu hoạch"
                    ),
                ),
                (
                    "blockchain_tx_hash",
                    models.CharField(
                        blank=True,
                        max_length=66,
                        null=True,
                        verbose_name="TxHash khởi tạo lô",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lô sản phẩm",
                "verbose_name_plural": "Lô sản phẩm",
                "ordering": ["harvest_date", "seeding_date"],
            },
        ),
        migrations.CreateModel(
            name="BatchMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Tiêu đề mốc")),
                (
                    "description",
                    models.TextField(verbose_name="Mô tả kỹ thuật chăm sóc"),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Địa điểm thực hiện"),
                ),
                (
                    "actor",
                    models.CharField(max_length=100, verbose_name="Người thực hiện"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian ghi nhận"
                    ),
                ),
                (
                    "blockchain_tx_hash",
                    models.CharField(
                        blank=True,
                        max_length=66,
                        null=True,
                        verbose_name="TxHash cột mốc",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="products.batch",
                        verbose_name="Lô sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký lô hàng",
                "verbose_name_plural": "Nhật ký lô hàng",
                "ordering": ["timestamp"],
            },
        ),
    ]
