# Generated by Django 5.2.15 on 2026-07-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_product_batch_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchmilestone",
            name="parameters",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Thông số kỹ thuật"
            ),
        ),
    ]
