# Generated by Django 5.2.15 on 2026-07-06 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_batchmilestone_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batchmilestone",
            name="audit_opinion",
            field=models.TextField(blank=True, verbose_name="Ý kiến kiểm định"),
        ),
        migrations.AddField(
            model_name="batchmilestone",
            name="auditor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_milestones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kiểm định viên",
            ),
        ),
        migrations.AddField(
            model_name="batchmilestone",
            name="inspection_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Mã số biên bản kiểm thực"
            ),
        ),
        migrations.AddField(
            model_name="batchmilestone",
            name="milestone_type",
            field=models.CharField(
                choices=[("MANUAL", "Thủ công"), ("IOT", "Tự động (IoT)")],
                default="MANUAL",
                max_length=10,
                verbose_name="Loại nhật ký",
            ),
        ),
        migrations.AddField(
            model_name="batchmilestone",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_AUDIT", "Chờ kiểm định"),
                    ("VERIFIED", "Đã xác thực"),
                    ("REJECTED", "Bị từ chối"),
                ],
                default="PENDING_AUDIT",
                max_length=20,
                verbose_name="Trạng thái kiểm định",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="business_license",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="licenses/",
                verbose_name="Ảnh Giấy phép kinh doanh",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="last_audit_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày kiểm định gần nhất"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="next_audit_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Hạn kiểm định tiếp theo"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_ADMIN", "Chờ Admin duyệt sơ bộ"),
                    ("PENDING_AUDITOR", "Chờ Kiểm định viên duyệt"),
                    ("APPROVED", "Đã duyệt & Cấp chứng chỉ"),
                    ("REJECTED", "Bị từ chối"),
                    ("SUSPENDED", "Bị đình chỉ hoạt động"),
                ],
                default="PENDING_ADMIN",
                max_length=20,
                verbose_name="Trạng thái duyệt",
            ),
        ),
        migrations.CreateModel(
            name="FarmAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_date",
                    models.DateField(auto_now_add=True, verbose_name="Ngày kiểm định"),
                ),
                ("result", models.BooleanField(verbose_name="Đạt yêu cầu")),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Ý kiến nhận xét/Đánh giá"
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kiểm định viên",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="products.farm",
                        verbose_name="Nông trại",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá nông trại",
                "verbose_name_plural": "Đánh giá nông trại",
                "ordering": ["-audit_date"],
            },
        ),
    ]
