# Generated by Django 5.2.15 on 2026-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0012_batchmilestone_audit_opinion_batchmilestone_auditor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_ADMIN", "Chờ Admin duyệt"),
                    ("PENDING_AUDITOR", "Chờ Kiểm định viên duyệt"),
                    ("APPROVED", "Đã duyệt"),
                    ("REJECTED", "Từ chối"),
                ],
                default="PENDING_ADMIN",
                max_length=20,
                verbose_name="Trạng thái duyệt",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=False, verbose_name="Còn hàng"),
        ),
    ]
