# Generated by Django 5.2.15 on 2026-07-06 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_product_status_alter_product_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Tên nhà cung cấp",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Số điện thoại liên hệ phải bắt đầu bằng số 0 và gồm 10 hoặc 11 chữ số.",
                        regex="^0\\d{9,10}$",
                    )
                ],
                verbose_name="Số điện thoại liên hệ",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="tax_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mã số thuế phải gồm 10 chữ số hoặc 13 chữ số (ví dụ: 1234567890 hoặc 1234567890-123).",
                        regex="^\\d{10}$|^\\d{13}$|^\\d{10}-\\d{3}$",
                    )
                ],
                verbose_name="Mã số thuế",
            ),
        ),
    ]
