# Generated by Django 5.2.15 on 2026-07-06 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_farm_name_alter_farm_phone_alter_farm_tax_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="business_license",
            field=models.FileField(
                null=True,
                upload_to="licenses/",
                verbose_name="Ảnh Giấy phép kinh doanh",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email liên hệ"),
        ),
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Số điện thoại liên hệ phải bắt đầu bằng số 0 và gồm 10 hoặc 11 chữ số.",
                        regex="^0\\d{9,10}$",
                    )
                ],
                verbose_name="Số điện thoại liên hệ",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="tax_code",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mã số thuế phải gồm 10 chữ số hoặc 13 chữ số (ví dụ: 1234567890 hoặc 1234567890-123).",
                        regex="^\\d{10}$|^\\d{13}$|^\\d{10}-\\d{3}$",
                    )
                ],
                verbose_name="Mã số thuế",
            ),
        ),
    ]
