# Generated by Django 5.2.15 on 2026-07-06 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_farm_business_license_alter_farm_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="initial_quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Số lượng gieo giống ban đầu",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="remaining_quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Số lượng tồn kho của lô",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1000)],
                verbose_name="Giá bán (VND)",
            ),
        ),
    ]
